week7/shopping_cart/shopping_cart/cart/urls.py
from django.conf.urls import url
from . import views

app_name = "cart"

urlpatterns = [
    url(r'^categories/$', views.CategoryList.as_view(), name="categories"),
    url(r'^categories/(?P<cat_id>\d+)/$', views.show_category, name="show_category" ),
    url(r'^add_to_cart/$', views.add_to_cart, name='add_to_cart'),
    url(r'^cart/$', views.show_cart, name='show_cart'),
]

week7/shopping_cart/shopping_cart/shopping_cart/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'', include('cart.urls')),
    url(r'^admin/', admin.site.urls),
]

week7/shopping_cart/shopping_cart/cart/models.py
from django.db import models
from django.contrib.auth.models import User

class Product(models.Model):
    name = models.CharField(max_length=140)
    price = models.FloatField()
    description = models.TextField()

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=140)
    products = models.ManyToManyField(Product)
    is_featured = models.BooleanField(default=False)

    def __str__(self):
        return self.name


class Cart(models.Model):
    products = models.ManyToManyField(Product)
    user = models.OneToOneField(User, null=True)

    def get_total(self):
        total = 0
        for product in self.products.all():
            total += product.price
        return total

week7/shopping_cart/shopping_cart/cart/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from .models import Category, Product, Cart
from django.views.generic.list import ListView


class CategoryList(ListView):
    model = Category

    context_object_name = 'categories'

# def categories(request):
#     categories = Category.objects.all().order_by('-is_featured')
#
#     context = {"categories" : categories}
#     return render(request, "category/index.html", context)

def show_category(request, cat_id):
    specific_cat = get_object_or_404(Category, id=cat_id)
    context = {"category": specific_cat}
    return render(request, "category/show.html", context)

def add_to_cart(request):
    if request.POST:
        product = Product.objects.get(id=request.POST['product_id'])
        cart, _ = Cart.objects.get_or_create(user=request.user)
        cart.products.add(product)
    return HttpResponseRedirect("/cart")

def show_cart(request):
    cart, _ = Cart.objects.get_or_create(user=request.user)
    context = {"cart": cart}
    return render(request, "category/cart.html", context)

week7/shopping_cart/shopping_cart/cart/templates/cart/category_list.html
<ul>
  {% for category in categories %}
  <li>
    <div><a href="{% url 'cart:show_category' category.id %}">{{ category }}</a></div>
  </li>
  {% endfor %}
</ul>

week7/shopping_cart/shopping_cart/cart/templates/category/cart.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'cart/style.css' %}" />


<ul>
  {% for product in cart.products.all %}
  <li> {{product.name}}; {{product.price}} </li>
  {% endfor %}
</ul>

Total price: {{cart.get_total}}

week7/shopping_cart/shopping_cart/cart/templates/category/show.html
{{ category }}

<ul>
  {% for product in category.products.all %}
    <li>
      <form action="{% url 'cart:add_to_cart' %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="product_id" value="{{product.id}}">
        <input type="submit" value="Add {{product}} to cart">
      </form>
    </li>
  {% endfor %}
</ul>